### PR TITLE
Change return type of size() from unsigned int to size_t

### PR DESCRIPTION
**Pull request by bendavp**
Title. We think most teams are more comfortable using `size_t` as opposed to `unsigned int`, if that's ok. They're essentially the same anyways. 

EDIT: Just added another change, adding the `initialize()` function to the `Queue` class. Unfortunately as per [Piazza post @322](https://piazza.com/class/k51bluky59n2jr?cid=322), because our group needs to initialize some constants in our header, we need the `static void initialize()` function in the API. We also need this function to be called _first_ in the test file, before the creation of any `Queue` objects, as the constant must be initialized first for our constructor to work. 

Hopefully this will not affect other teams too much, as they can just have one line in the `initialize()` function that reads `return;`, which will basically make the function do nothing, and not affect any of the tests.

Thanks in advance!

### CODE REVIEW

**Comment by njhofmann** [comment]
We defaulted to unsigned int since we didn't have size_t through the cstring lib, but it is reasonable to do a typedef for size_t. I'll do this tomorrow.

As for the initalize function and the Piazza post you linked, I think we are inclined to decline your suggestion since constants aren't established to be apart of CwC - and the the method Prof. Vitek posted feel cumbersome to say the least.. I think it would be easier for all if your group just veered away from the idea of trying to do constants than use adding another helper method that would essentially be useless for every other group (I assume).

So unless other groups are are clamoring for this feature, or you have another reason why we should add the method, we will have to say no to this pull request for now.

**Comment by bendavp** [comment]
No problem, we have leaned away from using constants.

JSYK, your test file won't work because in `string_queue_advanced_usage()` and `object_queue_advanced_usage()`, at the end of the function you delete `string1`, `string2`, and `string3`. This will cause a segfault, as you already delete the queues that contain those `String`s, so you are trying to delete `String`s that don't exist. It is fixed in my version but should be fixed in your tests so that other groups can see the change and their tests can pass. 

Thanks in advance for your support!!

**Comment by bendavp** [comment]
Also, see #17. I closed it since changing the tests are unnecessary but I realize you can't see it if I close it... lol. Anyways, the main Queue class should be reverted back to when there was an ObjectQueue and a StringQueue, as the API doesn't match the tests right now. 

I know I was originally the one to change it to just one Queue, but after understanding the point of the assignment better and reading the endless stream of Piazza posts, I think that your original design was better. My apologies for changing it! 

I think if you just remove my commits then that would do it. Thanks!

**Comment by njhofmann** [comment]
Thanks for the heads up on the delete statements, that's something I'll look over later. The intention is that Objects passed to the Queue should not be deleted when the Queue is deleted. You should be able to pass an Object to multiples Queues without issues.

As for bring back the StringQueue, we've already removed it from a prior PR so reintroducing it would probably be a bad idea at this point. Plus we've decided that its probably easiest for all to just have one class and casting.

**Comment by bendavp** [comment]
Sure, it may be easier, but it will seriously hurt the performance of the Queue.

What is the intention of having one Queue? Is it only storing one type of Object? i.e. can I store both Strings and Objects in there? If so, what happens when I want to make sure that my Queue contains only Strings? There isn't really any way to guarantee that if the Queue can support storing any Object. If I can't store both Strings and Objects, there will be a LOT of casting involved in the implementation, again, seriously hurting the performance of the Queue. 

IMO, the best compromise is to have some code duplication, but allow the user ultimate flexibility by having both a weak-typed and a strong-typed Queue (i.e. one that can store any Object and one that can store only Strings). The implementation will be much more light, as there will be no casting involved. 

In light of these advantages, plus the latest Piazza answers from Jan strongly hinting that it is better to duplicate code in the name of flexibility and efficiency [see Piazza post @331](https://piazza.com/class/k51bluky59n2jr?cid=331), I think you are making a mistake by sticking to one Queue. 

But ultimately, you are free to make your own design decisions. TBH we have already implemented your old design and we will probably just stick to it as we don't want to rewrite everything from scratch.

**Comment by mwaldrich** [comment]
Please don't change the Queue API to require a StringQueue and an ObjectQueue. You can easily subclass the main Queue class and abstract away the casting. Additionally, if you use `static_cast`, there should be no performance hit.

**Comment by njhofmann** [comment]
Yeah all your points are valid, I don't necessairly disagree with anything you're saying. We would probably would've kept the original design of two separate APIs, but since we already got rid of StringQueue as per the request of another PR - we feel like it would be a obnoxious hassle for us to make such a large change by reverting the change with the assignment deadline tomorrow. 

So I'm not disagreeing with you on the topic of separate APIs, I just don't want to induce more work for other groups. In hindsight we probably wouldn't have done that change, it would've been better to have a more strict interpretation of the spec.. I hope you understand where we're coming from.

On the topic of code duplication vs performance, I personally value reducing code duplicate over performance for the scale that this assignment deals with. I would rather have type specific queues  for things like primitives and Strings that are easier to maintain because they simply rely on Queue for all the underlying operations via composition, wrapper classes, and casting - even it means that code is slower by some large constant factor. I don't think there is a "best compromise"  necessarily, just a matter of preference.

**Pull request closed without merging**
